# Generated by Django 4.1.1 on 2022-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('nickname', models.TextField()),
                ('biography', models.TextField()),
                ('organization', models.TextField()),
                ('location', models.TextField()),
                ('profile_website', models.TextField()),
                ('twitter_account', models.TextField()),
                ('popular_repositories', models.TextField()),
                ('all_repositories', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='feature',
        ),
    ]
